/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Youth4workRouteImport } from './routes/youth4work'
import { Route as WomenCellRouteImport } from './routes/women-cell'
import { Route as VtuMinorDegreeRouteImport } from './routes/vtu-minor-degree'
import { Route as VtuHonorDegreeRouteImport } from './routes/vtu-honor-degree'
import { Route as VirtualLabRouteImport } from './routes/virtual-lab'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as StudentHandbookRouteImport } from './routes/student-handbook'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProfessionalBodyMembershipRouteImport } from './routes/professional-body-membership'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as NirfRouteImport } from './routes/nirf'
import { Route as NewsClippingsRouteImport } from './routes/news-clippings'
import { Route as NablRouteImport } from './routes/nabl'
import { Route as MandatoryDisclosureRouteImport } from './routes/mandatory-disclosure'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IirsIsroNcRouteImport } from './routes/iirs-isro-nc'
import { Route as HostelPolicyRouteImport } from './routes/hostel-policy'
import { Route as EmployeeHandbookRouteImport } from './routes/employee-handbook'
import { Route as CyberarmorRegistrationRouteImport } from './routes/cyberarmor-registration'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CircularsRouteImport } from './routes/circulars'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CampusTourRouteImport } from './routes/campus-tour'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as CampusLifeIndexRouteImport } from './routes/campus-life.index'
import { Route as ResourcesVideosRouteImport } from './routes/resources.videos'
import { Route as ResourcesPlacementRouteImport } from './routes/resources.placement'
import { Route as ResourcesPapersRouteImport } from './routes/resources.papers'
import { Route as ResourcesNotesRouteImport } from './routes/resources.notes'
import { Route as ResourcesElibraryRouteImport } from './routes/resources.elibrary'
import { Route as ResourcesDiscreteMathematicalStructuresRouteImport } from './routes/resources.discrete-mathematical-structures'
import { Route as ResearchPageRouteImport } from './routes/research.$page'
import { Route as PSplatRouteImport } from './routes/p.$'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as CampusLifeEventsRouteImport } from './routes/campus-life.events'
import { Route as CampusLifeAtmeyaRouteImport } from './routes/campus-life.atmeya'
import { Route as CampusLifePageRouteImport } from './routes/campus-life.$page'
import { Route as AdminRescrapeRouteImport } from './routes/admin.rescrape'
import { Route as AboutPageRouteImport } from './routes/about_.$page'
import { Route as DepartmentsSlugIndexRouteImport } from './routes/departments.$slug.index'
import { Route as DepartmentsSlugPageRouteImport } from './routes/departments.$slug.$page'
import { Route as ApiAdminRescrapeFacultyRouteImport } from './routes/api.admin.rescrape-faculty'
import { Route as DepartmentsSlugFacultyIndexRouteImport } from './routes/departments.$slug.faculty.index'
import { Route as DepartmentsSlugFacultyFacultyIdRouteImport } from './routes/departments.$slug.faculty.$facultyId'

const Youth4workRoute = Youth4workRouteImport.update({
  id: '/youth4work',
  path: '/youth4work',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenCellRoute = WomenCellRouteImport.update({
  id: '/women-cell',
  path: '/women-cell',
  getParentRoute: () => rootRouteImport,
} as any)
const VtuMinorDegreeRoute = VtuMinorDegreeRouteImport.update({
  id: '/vtu-minor-degree',
  path: '/vtu-minor-degree',
  getParentRoute: () => rootRouteImport,
} as any)
const VtuHonorDegreeRoute = VtuHonorDegreeRouteImport.update({
  id: '/vtu-honor-degree',
  path: '/vtu-honor-degree',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualLabRoute = VirtualLabRouteImport.update({
  id: '/virtual-lab',
  path: '/virtual-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHandbookRoute = StudentHandbookRouteImport.update({
  id: '/student-handbook',
  path: '/student-handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalBodyMembershipRoute =
  ProfessionalBodyMembershipRouteImport.update({
    id: '/professional-body-membership',
    path: '/professional-body-membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const NirfRoute = NirfRouteImport.update({
  id: '/nirf',
  path: '/nirf',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsClippingsRoute = NewsClippingsRouteImport.update({
  id: '/news-clippings',
  path: '/news-clippings',
  getParentRoute: () => rootRouteImport,
} as any)
const NablRoute = NablRouteImport.update({
  id: '/nabl',
  path: '/nabl',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDisclosureRoute = MandatoryDisclosureRouteImport.update({
  id: '/mandatory-disclosure',
  path: '/mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IirsIsroNcRoute = IirsIsroNcRouteImport.update({
  id: '/iirs-isro-nc',
  path: '/iirs-isro-nc',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelPolicyRoute = HostelPolicyRouteImport.update({
  id: '/hostel-policy',
  path: '/hostel-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeHandbookRoute = EmployeeHandbookRouteImport.update({
  id: '/employee-handbook',
  path: '/employee-handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberarmorRegistrationRoute = CyberarmorRegistrationRouteImport.update({
  id: '/cyberarmor-registration',
  path: '/cyberarmor-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsRoute = CircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusTourRoute = CampusTourRouteImport.update({
  id: '/campus-tour',
  path: '/campus-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeIndexRoute = CampusLifeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusLifeRoute,
} as any)
const ResourcesVideosRoute = ResourcesVideosRouteImport.update({
  id: '/resources/videos',
  path: '/resources/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPlacementRoute = ResourcesPlacementRouteImport.update({
  id: '/resources/placement',
  path: '/resources/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesPapersRoute = ResourcesPapersRouteImport.update({
  id: '/resources/papers',
  path: '/resources/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNotesRoute = ResourcesNotesRouteImport.update({
  id: '/resources/notes',
  path: '/resources/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesElibraryRoute = ResourcesElibraryRouteImport.update({
  id: '/resources/elibrary',
  path: '/resources/elibrary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesDiscreteMathematicalStructuresRoute =
  ResourcesDiscreteMathematicalStructuresRouteImport.update({
    id: '/resources/discrete-mathematical-structures',
    path: '/resources/discrete-mathematical-structures',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResearchPageRoute = ResearchPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ResearchRoute,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeEventsRoute = CampusLifeEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CampusLifeRoute,
} as any)
const CampusLifeAtmeyaRoute = CampusLifeAtmeyaRouteImport.update({
  id: '/atmeya',
  path: '/atmeya',
  getParentRoute: () => CampusLifeRoute,
} as any)
const CampusLifePageRoute = CampusLifePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => CampusLifeRoute,
} as any)
const AdminRescrapeRoute = AdminRescrapeRouteImport.update({
  id: '/admin/rescrape',
  path: '/admin/rescrape',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPageRoute = AboutPageRouteImport.update({
  id: '/about_/$page',
  path: '/about/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugIndexRoute = DepartmentsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DepartmentsSlugRoute,
} as any)
const DepartmentsSlugPageRoute = DepartmentsSlugPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => DepartmentsSlugRoute,
} as any)
const ApiAdminRescrapeFacultyRoute = ApiAdminRescrapeFacultyRouteImport.update({
  id: '/api/admin/rescrape-faculty',
  path: '/api/admin/rescrape-faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugFacultyIndexRoute =
  DepartmentsSlugFacultyIndexRouteImport.update({
    id: '/faculty/',
    path: '/faculty/',
    getParentRoute: () => DepartmentsSlugRoute,
  } as any)
const DepartmentsSlugFacultyFacultyIdRoute =
  DepartmentsSlugFacultyFacultyIdRouteImport.update({
    id: '/faculty/$facultyId',
    path: '/faculty/$facultyId',
    getParentRoute: () => DepartmentsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRouteWithChildren
  '/campus-tour': typeof CampusTourRoute
  '/careers': typeof CareersRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/cyberarmor-registration': typeof CyberarmorRegistrationRoute
  '/employee-handbook': typeof EmployeeHandbookRoute
  '/hostel-policy': typeof HostelPolicyRoute
  '/iirs-isro-nc': typeof IirsIsroNcRoute
  '/library': typeof LibraryRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/nabl': typeof NablRoute
  '/news-clippings': typeof NewsClippingsRoute
  '/nirf': typeof NirfRoute
  '/placements': typeof PlacementsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/professional-body-membership': typeof ProfessionalBodyMembershipRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/student-handbook': typeof StudentHandbookRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/virtual-lab': typeof VirtualLabRoute
  '/vtu-honor-degree': typeof VtuHonorDegreeRoute
  '/vtu-minor-degree': typeof VtuMinorDegreeRoute
  '/women-cell': typeof WomenCellRoute
  '/youth4work': typeof Youth4workRoute
  '/about/$page': typeof AboutPageRoute
  '/admin/rescrape': typeof AdminRescrapeRoute
  '/campus-life/$page': typeof CampusLifePageRoute
  '/campus-life/atmeya': typeof CampusLifeAtmeyaRoute
  '/campus-life/events': typeof CampusLifeEventsRoute
  '/departments/$slug': typeof DepartmentsSlugRouteWithChildren
  '/p/$': typeof PSplatRoute
  '/research/$page': typeof ResearchPageRoute
  '/resources/discrete-mathematical-structures': typeof ResourcesDiscreteMathematicalStructuresRoute
  '/resources/elibrary': typeof ResourcesElibraryRoute
  '/resources/notes': typeof ResourcesNotesRoute
  '/resources/papers': typeof ResourcesPapersRoute
  '/resources/placement': typeof ResourcesPlacementRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/admin/rescrape-faculty': typeof ApiAdminRescrapeFacultyRoute
  '/departments/$slug/$page': typeof DepartmentsSlugPageRoute
  '/departments/$slug/': typeof DepartmentsSlugIndexRoute
  '/departments/$slug/faculty/$facultyId': typeof DepartmentsSlugFacultyFacultyIdRoute
  '/departments/$slug/faculty/': typeof DepartmentsSlugFacultyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-tour': typeof CampusTourRoute
  '/careers': typeof CareersRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/cyberarmor-registration': typeof CyberarmorRegistrationRoute
  '/employee-handbook': typeof EmployeeHandbookRoute
  '/hostel-policy': typeof HostelPolicyRoute
  '/iirs-isro-nc': typeof IirsIsroNcRoute
  '/library': typeof LibraryRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/nabl': typeof NablRoute
  '/news-clippings': typeof NewsClippingsRoute
  '/nirf': typeof NirfRoute
  '/placements': typeof PlacementsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/professional-body-membership': typeof ProfessionalBodyMembershipRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/student-handbook': typeof StudentHandbookRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/virtual-lab': typeof VirtualLabRoute
  '/vtu-honor-degree': typeof VtuHonorDegreeRoute
  '/vtu-minor-degree': typeof VtuMinorDegreeRoute
  '/women-cell': typeof WomenCellRoute
  '/youth4work': typeof Youth4workRoute
  '/about/$page': typeof AboutPageRoute
  '/admin/rescrape': typeof AdminRescrapeRoute
  '/campus-life/$page': typeof CampusLifePageRoute
  '/campus-life/atmeya': typeof CampusLifeAtmeyaRoute
  '/campus-life/events': typeof CampusLifeEventsRoute
  '/p/$': typeof PSplatRoute
  '/research/$page': typeof ResearchPageRoute
  '/resources/discrete-mathematical-structures': typeof ResourcesDiscreteMathematicalStructuresRoute
  '/resources/elibrary': typeof ResourcesElibraryRoute
  '/resources/notes': typeof ResourcesNotesRoute
  '/resources/papers': typeof ResourcesPapersRoute
  '/resources/placement': typeof ResourcesPlacementRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/campus-life': typeof CampusLifeIndexRoute
  '/departments': typeof DepartmentsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/api/admin/rescrape-faculty': typeof ApiAdminRescrapeFacultyRoute
  '/departments/$slug/$page': typeof DepartmentsSlugPageRoute
  '/departments/$slug': typeof DepartmentsSlugIndexRoute
  '/departments/$slug/faculty/$facultyId': typeof DepartmentsSlugFacultyFacultyIdRoute
  '/departments/$slug/faculty': typeof DepartmentsSlugFacultyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRouteWithChildren
  '/campus-tour': typeof CampusTourRoute
  '/careers': typeof CareersRoute
  '/circulars': typeof CircularsRoute
  '/contact': typeof ContactRoute
  '/cyberarmor-registration': typeof CyberarmorRegistrationRoute
  '/employee-handbook': typeof EmployeeHandbookRoute
  '/hostel-policy': typeof HostelPolicyRoute
  '/iirs-isro-nc': typeof IirsIsroNcRoute
  '/library': typeof LibraryRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
  '/nabl': typeof NablRoute
  '/news-clippings': typeof NewsClippingsRoute
  '/nirf': typeof NirfRoute
  '/placements': typeof PlacementsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/professional-body-membership': typeof ProfessionalBodyMembershipRoute
  '/research': typeof ResearchRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/student-handbook': typeof StudentHandbookRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/virtual-lab': typeof VirtualLabRoute
  '/vtu-honor-degree': typeof VtuHonorDegreeRoute
  '/vtu-minor-degree': typeof VtuMinorDegreeRoute
  '/women-cell': typeof WomenCellRoute
  '/youth4work': typeof Youth4workRoute
  '/about_/$page': typeof AboutPageRoute
  '/admin/rescrape': typeof AdminRescrapeRoute
  '/campus-life/$page': typeof CampusLifePageRoute
  '/campus-life/atmeya': typeof CampusLifeAtmeyaRoute
  '/campus-life/events': typeof CampusLifeEventsRoute
  '/departments/$slug': typeof DepartmentsSlugRouteWithChildren
  '/p/$': typeof PSplatRoute
  '/research/$page': typeof ResearchPageRoute
  '/resources/discrete-mathematical-structures': typeof ResourcesDiscreteMathematicalStructuresRoute
  '/resources/elibrary': typeof ResourcesElibraryRoute
  '/resources/notes': typeof ResourcesNotesRoute
  '/resources/papers': typeof ResourcesPapersRoute
  '/resources/placement': typeof ResourcesPlacementRoute
  '/resources/videos': typeof ResourcesVideosRoute
  '/campus-life/': typeof CampusLifeIndexRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/api/admin/rescrape-faculty': typeof ApiAdminRescrapeFacultyRoute
  '/departments/$slug/$page': typeof DepartmentsSlugPageRoute
  '/departments/$slug/': typeof DepartmentsSlugIndexRoute
  '/departments/$slug/faculty/$facultyId': typeof DepartmentsSlugFacultyFacultyIdRoute
  '/departments/$slug/faculty/': typeof DepartmentsSlugFacultyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus-life'
    | '/campus-tour'
    | '/careers'
    | '/circulars'
    | '/contact'
    | '/cyberarmor-registration'
    | '/employee-handbook'
    | '/hostel-policy'
    | '/iirs-isro-nc'
    | '/library'
    | '/mandatory-disclosure'
    | '/nabl'
    | '/news-clippings'
    | '/nirf'
    | '/placements'
    | '/privacy-policy'
    | '/professional-body-membership'
    | '/research'
    | '/sitemap.xml'
    | '/sports'
    | '/student-handbook'
    | '/upcoming-events'
    | '/virtual-lab'
    | '/vtu-honor-degree'
    | '/vtu-minor-degree'
    | '/women-cell'
    | '/youth4work'
    | '/about/$page'
    | '/admin/rescrape'
    | '/campus-life/$page'
    | '/campus-life/atmeya'
    | '/campus-life/events'
    | '/departments/$slug'
    | '/p/$'
    | '/research/$page'
    | '/resources/discrete-mathematical-structures'
    | '/resources/elibrary'
    | '/resources/notes'
    | '/resources/papers'
    | '/resources/placement'
    | '/resources/videos'
    | '/campus-life/'
    | '/departments/'
    | '/resources/'
    | '/api/admin/rescrape-faculty'
    | '/departments/$slug/$page'
    | '/departments/$slug/'
    | '/departments/$slug/faculty/$facultyId'
    | '/departments/$slug/faculty/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus-tour'
    | '/careers'
    | '/circulars'
    | '/contact'
    | '/cyberarmor-registration'
    | '/employee-handbook'
    | '/hostel-policy'
    | '/iirs-isro-nc'
    | '/library'
    | '/mandatory-disclosure'
    | '/nabl'
    | '/news-clippings'
    | '/nirf'
    | '/placements'
    | '/privacy-policy'
    | '/professional-body-membership'
    | '/research'
    | '/sitemap.xml'
    | '/sports'
    | '/student-handbook'
    | '/upcoming-events'
    | '/virtual-lab'
    | '/vtu-honor-degree'
    | '/vtu-minor-degree'
    | '/women-cell'
    | '/youth4work'
    | '/about/$page'
    | '/admin/rescrape'
    | '/campus-life/$page'
    | '/campus-life/atmeya'
    | '/campus-life/events'
    | '/p/$'
    | '/research/$page'
    | '/resources/discrete-mathematical-structures'
    | '/resources/elibrary'
    | '/resources/notes'
    | '/resources/papers'
    | '/resources/placement'
    | '/resources/videos'
    | '/campus-life'
    | '/departments'
    | '/resources'
    | '/api/admin/rescrape-faculty'
    | '/departments/$slug/$page'
    | '/departments/$slug'
    | '/departments/$slug/faculty/$facultyId'
    | '/departments/$slug/faculty'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus-life'
    | '/campus-tour'
    | '/careers'
    | '/circulars'
    | '/contact'
    | '/cyberarmor-registration'
    | '/employee-handbook'
    | '/hostel-policy'
    | '/iirs-isro-nc'
    | '/library'
    | '/mandatory-disclosure'
    | '/nabl'
    | '/news-clippings'
    | '/nirf'
    | '/placements'
    | '/privacy-policy'
    | '/professional-body-membership'
    | '/research'
    | '/sitemap.xml'
    | '/sports'
    | '/student-handbook'
    | '/upcoming-events'
    | '/virtual-lab'
    | '/vtu-honor-degree'
    | '/vtu-minor-degree'
    | '/women-cell'
    | '/youth4work'
    | '/about_/$page'
    | '/admin/rescrape'
    | '/campus-life/$page'
    | '/campus-life/atmeya'
    | '/campus-life/events'
    | '/departments/$slug'
    | '/p/$'
    | '/research/$page'
    | '/resources/discrete-mathematical-structures'
    | '/resources/elibrary'
    | '/resources/notes'
    | '/resources/papers'
    | '/resources/placement'
    | '/resources/videos'
    | '/campus-life/'
    | '/departments/'
    | '/resources/'
    | '/api/admin/rescrape-faculty'
    | '/departments/$slug/$page'
    | '/departments/$slug/'
    | '/departments/$slug/faculty/$facultyId'
    | '/departments/$slug/faculty/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdministrationRoute: typeof AdministrationRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusLifeRoute: typeof CampusLifeRouteWithChildren
  CampusTourRoute: typeof CampusTourRoute
  CareersRoute: typeof CareersRoute
  CircularsRoute: typeof CircularsRoute
  ContactRoute: typeof ContactRoute
  CyberarmorRegistrationRoute: typeof CyberarmorRegistrationRoute
  EmployeeHandbookRoute: typeof EmployeeHandbookRoute
  HostelPolicyRoute: typeof HostelPolicyRoute
  IirsIsroNcRoute: typeof IirsIsroNcRoute
  LibraryRoute: typeof LibraryRoute
  MandatoryDisclosureRoute: typeof MandatoryDisclosureRoute
  NablRoute: typeof NablRoute
  NewsClippingsRoute: typeof NewsClippingsRoute
  NirfRoute: typeof NirfRoute
  PlacementsRoute: typeof PlacementsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfessionalBodyMembershipRoute: typeof ProfessionalBodyMembershipRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  StudentHandbookRoute: typeof StudentHandbookRoute
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  VirtualLabRoute: typeof VirtualLabRoute
  VtuHonorDegreeRoute: typeof VtuHonorDegreeRoute
  VtuMinorDegreeRoute: typeof VtuMinorDegreeRoute
  WomenCellRoute: typeof WomenCellRoute
  Youth4workRoute: typeof Youth4workRoute
  AboutPageRoute: typeof AboutPageRoute
  AdminRescrapeRoute: typeof AdminRescrapeRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRouteWithChildren
  PSplatRoute: typeof PSplatRoute
  ResourcesDiscreteMathematicalStructuresRoute: typeof ResourcesDiscreteMathematicalStructuresRoute
  ResourcesElibraryRoute: typeof ResourcesElibraryRoute
  ResourcesNotesRoute: typeof ResourcesNotesRoute
  ResourcesPapersRoute: typeof ResourcesPapersRoute
  ResourcesPlacementRoute: typeof ResourcesPlacementRoute
  ResourcesVideosRoute: typeof ResourcesVideosRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAdminRescrapeFacultyRoute: typeof ApiAdminRescrapeFacultyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth4work': {
      id: '/youth4work'
      path: '/youth4work'
      fullPath: '/youth4work'
      preLoaderRoute: typeof Youth4workRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women-cell': {
      id: '/women-cell'
      path: '/women-cell'
      fullPath: '/women-cell'
      preLoaderRoute: typeof WomenCellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtu-minor-degree': {
      id: '/vtu-minor-degree'
      path: '/vtu-minor-degree'
      fullPath: '/vtu-minor-degree'
      preLoaderRoute: typeof VtuMinorDegreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vtu-honor-degree': {
      id: '/vtu-honor-degree'
      path: '/vtu-honor-degree'
      fullPath: '/vtu-honor-degree'
      preLoaderRoute: typeof VtuHonorDegreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-lab': {
      id: '/virtual-lab'
      path: '/virtual-lab'
      fullPath: '/virtual-lab'
      preLoaderRoute: typeof VirtualLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-handbook': {
      id: '/student-handbook'
      path: '/student-handbook'
      fullPath: '/student-handbook'
      preLoaderRoute: typeof StudentHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-body-membership': {
      id: '/professional-body-membership'
      path: '/professional-body-membership'
      fullPath: '/professional-body-membership'
      preLoaderRoute: typeof ProfessionalBodyMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nirf': {
      id: '/nirf'
      path: '/nirf'
      fullPath: '/nirf'
      preLoaderRoute: typeof NirfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-clippings': {
      id: '/news-clippings'
      path: '/news-clippings'
      fullPath: '/news-clippings'
      preLoaderRoute: typeof NewsClippingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nabl': {
      id: '/nabl'
      path: '/nabl'
      fullPath: '/nabl'
      preLoaderRoute: typeof NablRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-disclosure': {
      id: '/mandatory-disclosure'
      path: '/mandatory-disclosure'
      fullPath: '/mandatory-disclosure'
      preLoaderRoute: typeof MandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iirs-isro-nc': {
      id: '/iirs-isro-nc'
      path: '/iirs-isro-nc'
      fullPath: '/iirs-isro-nc'
      preLoaderRoute: typeof IirsIsroNcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel-policy': {
      id: '/hostel-policy'
      path: '/hostel-policy'
      fullPath: '/hostel-policy'
      preLoaderRoute: typeof HostelPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-handbook': {
      id: '/employee-handbook'
      path: '/employee-handbook'
      fullPath: '/employee-handbook'
      preLoaderRoute: typeof EmployeeHandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberarmor-registration': {
      id: '/cyberarmor-registration'
      path: '/cyberarmor-registration'
      fullPath: '/cyberarmor-registration'
      preLoaderRoute: typeof CyberarmorRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars': {
      id: '/circulars'
      path: '/circulars'
      fullPath: '/circulars'
      preLoaderRoute: typeof CircularsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-tour': {
      id: '/campus-tour'
      path: '/campus-tour'
      fullPath: '/campus-tour'
      preLoaderRoute: typeof CampusTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life/': {
      id: '/campus-life/'
      path: '/'
      fullPath: '/campus-life/'
      preLoaderRoute: typeof CampusLifeIndexRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/resources/videos': {
      id: '/resources/videos'
      path: '/resources/videos'
      fullPath: '/resources/videos'
      preLoaderRoute: typeof ResourcesVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/placement': {
      id: '/resources/placement'
      path: '/resources/placement'
      fullPath: '/resources/placement'
      preLoaderRoute: typeof ResourcesPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/papers': {
      id: '/resources/papers'
      path: '/resources/papers'
      fullPath: '/resources/papers'
      preLoaderRoute: typeof ResourcesPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/notes': {
      id: '/resources/notes'
      path: '/resources/notes'
      fullPath: '/resources/notes'
      preLoaderRoute: typeof ResourcesNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/elibrary': {
      id: '/resources/elibrary'
      path: '/resources/elibrary'
      fullPath: '/resources/elibrary'
      preLoaderRoute: typeof ResourcesElibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/discrete-mathematical-structures': {
      id: '/resources/discrete-mathematical-structures'
      path: '/resources/discrete-mathematical-structures'
      fullPath: '/resources/discrete-mathematical-structures'
      preLoaderRoute: typeof ResourcesDiscreteMathematicalStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$page': {
      id: '/research/$page'
      path: '/$page'
      fullPath: '/research/$page'
      preLoaderRoute: typeof ResearchPageRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life/events': {
      id: '/campus-life/events'
      path: '/events'
      fullPath: '/campus-life/events'
      preLoaderRoute: typeof CampusLifeEventsRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/campus-life/atmeya': {
      id: '/campus-life/atmeya'
      path: '/atmeya'
      fullPath: '/campus-life/atmeya'
      preLoaderRoute: typeof CampusLifeAtmeyaRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/campus-life/$page': {
      id: '/campus-life/$page'
      path: '/$page'
      fullPath: '/campus-life/$page'
      preLoaderRoute: typeof CampusLifePageRouteImport
      parentRoute: typeof CampusLifeRoute
    }
    '/admin/rescrape': {
      id: '/admin/rescrape'
      path: '/admin/rescrape'
      fullPath: '/admin/rescrape'
      preLoaderRoute: typeof AdminRescrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/$page': {
      id: '/about_/$page'
      path: '/about/$page'
      fullPath: '/about/$page'
      preLoaderRoute: typeof AboutPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug/': {
      id: '/departments/$slug/'
      path: '/'
      fullPath: '/departments/$slug/'
      preLoaderRoute: typeof DepartmentsSlugIndexRouteImport
      parentRoute: typeof DepartmentsSlugRoute
    }
    '/departments/$slug/$page': {
      id: '/departments/$slug/$page'
      path: '/$page'
      fullPath: '/departments/$slug/$page'
      preLoaderRoute: typeof DepartmentsSlugPageRouteImport
      parentRoute: typeof DepartmentsSlugRoute
    }
    '/api/admin/rescrape-faculty': {
      id: '/api/admin/rescrape-faculty'
      path: '/api/admin/rescrape-faculty'
      fullPath: '/api/admin/rescrape-faculty'
      preLoaderRoute: typeof ApiAdminRescrapeFacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug/faculty/': {
      id: '/departments/$slug/faculty/'
      path: '/faculty'
      fullPath: '/departments/$slug/faculty/'
      preLoaderRoute: typeof DepartmentsSlugFacultyIndexRouteImport
      parentRoute: typeof DepartmentsSlugRoute
    }
    '/departments/$slug/faculty/$facultyId': {
      id: '/departments/$slug/faculty/$facultyId'
      path: '/faculty/$facultyId'
      fullPath: '/departments/$slug/faculty/$facultyId'
      preLoaderRoute: typeof DepartmentsSlugFacultyFacultyIdRouteImport
      parentRoute: typeof DepartmentsSlugRoute
    }
  }
}

interface CampusLifeRouteChildren {
  CampusLifePageRoute: typeof CampusLifePageRoute
  CampusLifeAtmeyaRoute: typeof CampusLifeAtmeyaRoute
  CampusLifeEventsRoute: typeof CampusLifeEventsRoute
  CampusLifeIndexRoute: typeof CampusLifeIndexRoute
}

const CampusLifeRouteChildren: CampusLifeRouteChildren = {
  CampusLifePageRoute: CampusLifePageRoute,
  CampusLifeAtmeyaRoute: CampusLifeAtmeyaRoute,
  CampusLifeEventsRoute: CampusLifeEventsRoute,
  CampusLifeIndexRoute: CampusLifeIndexRoute,
}

const CampusLifeRouteWithChildren = CampusLifeRoute._addFileChildren(
  CampusLifeRouteChildren,
)

interface ResearchRouteChildren {
  ResearchPageRoute: typeof ResearchPageRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchPageRoute: ResearchPageRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

interface DepartmentsSlugRouteChildren {
  DepartmentsSlugPageRoute: typeof DepartmentsSlugPageRoute
  DepartmentsSlugIndexRoute: typeof DepartmentsSlugIndexRoute
  DepartmentsSlugFacultyFacultyIdRoute: typeof DepartmentsSlugFacultyFacultyIdRoute
  DepartmentsSlugFacultyIndexRoute: typeof DepartmentsSlugFacultyIndexRoute
}

const DepartmentsSlugRouteChildren: DepartmentsSlugRouteChildren = {
  DepartmentsSlugPageRoute: DepartmentsSlugPageRoute,
  DepartmentsSlugIndexRoute: DepartmentsSlugIndexRoute,
  DepartmentsSlugFacultyFacultyIdRoute: DepartmentsSlugFacultyFacultyIdRoute,
  DepartmentsSlugFacultyIndexRoute: DepartmentsSlugFacultyIndexRoute,
}

const DepartmentsSlugRouteWithChildren = DepartmentsSlugRoute._addFileChildren(
  DepartmentsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdministrationRoute: AdministrationRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusLifeRoute: CampusLifeRouteWithChildren,
  CampusTourRoute: CampusTourRoute,
  CareersRoute: CareersRoute,
  CircularsRoute: CircularsRoute,
  ContactRoute: ContactRoute,
  CyberarmorRegistrationRoute: CyberarmorRegistrationRoute,
  EmployeeHandbookRoute: EmployeeHandbookRoute,
  HostelPolicyRoute: HostelPolicyRoute,
  IirsIsroNcRoute: IirsIsroNcRoute,
  LibraryRoute: LibraryRoute,
  MandatoryDisclosureRoute: MandatoryDisclosureRoute,
  NablRoute: NablRoute,
  NewsClippingsRoute: NewsClippingsRoute,
  NirfRoute: NirfRoute,
  PlacementsRoute: PlacementsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfessionalBodyMembershipRoute: ProfessionalBodyMembershipRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  StudentHandbookRoute: StudentHandbookRoute,
  UpcomingEventsRoute: UpcomingEventsRoute,
  VirtualLabRoute: VirtualLabRoute,
  VtuHonorDegreeRoute: VtuHonorDegreeRoute,
  VtuMinorDegreeRoute: VtuMinorDegreeRoute,
  WomenCellRoute: WomenCellRoute,
  Youth4workRoute: Youth4workRoute,
  AboutPageRoute: AboutPageRoute,
  AdminRescrapeRoute: AdminRescrapeRoute,
  DepartmentsSlugRoute: DepartmentsSlugRouteWithChildren,
  PSplatRoute: PSplatRoute,
  ResourcesDiscreteMathematicalStructuresRoute:
    ResourcesDiscreteMathematicalStructuresRoute,
  ResourcesElibraryRoute: ResourcesElibraryRoute,
  ResourcesNotesRoute: ResourcesNotesRoute,
  ResourcesPapersRoute: ResourcesPapersRoute,
  ResourcesPlacementRoute: ResourcesPlacementRoute,
  ResourcesVideosRoute: ResourcesVideosRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAdminRescrapeFacultyRoute: ApiAdminRescrapeFacultyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
